<a href="https://colab.research.google.com/github/cs-mama/DMDW-Assignment-Sem-5/blob/main/18cse068_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#ASSIGNMENT 2
#10 programs using numpy library

import numpy  as np

#1D array
a=np.array([1,2,3])
print(a)

#2D array
a=np.array([(1,2,3),(4,5,6)])
print(a)

#finding the dimension of array
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

#finding the itemsize
a = np.array([(1,2,3)])
print(a.itemsize)

#finding the particular datatype
a = np.array([(1,2,3)])
print(a.dtype)

#finding the size and dimension of array
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

#reshaping the dimensions
a = np.array([(8,9,10),(11,12,13)])
a=a.reshape(3,2)                   #2,3 dimensional matrix is converted to 3,2
print(a)

#FINDING THE MAX,MIN AND  sum
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

#multiplications subtraction and division of two matrices
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)

[1 2 3]
[[1 2 3]
 [4 5 6]]
2
8
int64
6
(1, 6)
[[ 8  9]
 [10 11]
 [12 13]]
1
3
6
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
from google.colab import files 
uploaded = files.upload()

Saving Bank_churn_modelling.csv to Bank_churn_modelling.csv


In [3]:
#uploading the dataset
import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['Bank_churn_modelling.csv'])) 
print(df)

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10

In [4]:
#checking for missing values
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.shape #dimensions of data set in terms of rows and columns

(10000, 14)

In [6]:
df.columns#printing columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [7]:
df.info()#object represents the string datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [8]:
df.describe() #it describe the statistcal data std-standard deviation

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [9]:
#check for unique values in geography 
df.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
#check for duplicates
df.duplicated().sum()

0